import { MigrationInterface, QueryRunner } from "typeorm";

export class FixAutoGeneratedUUIDAppointment1693902167326 implements MigrationInterface {
    name = 'FixAutoGeneratedUUIDAppointment1693902167326'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "appointment_guest" DROP CONSTRAINT "FK_0bad2851364dbc370bad0683c53"`);
        await queryRunner.query(`ALTER TABLE "appointment_translation" DROP CONSTRAINT "FK_3e21fd50c9d1be374b3b620002c"`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "appointment_translation" ADD CONSTRAINT "FK_3e21fd50c9d1be374b3b620002c" FOREIGN KEY ("translatableId") REFERENCES "appointment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_guest" ADD CONSTRAINT "FK_0bad2851364dbc370bad0683c53" FOREIGN KEY ("appointmentId") REFERENCES "appointment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "appointment_guest" DROP CONSTRAINT "FK_0bad2851364dbc370bad0683c53"`);
        await queryRunner.query(`ALTER TABLE "appointment_translation" DROP CONSTRAINT "FK_3e21fd50c9d1be374b3b620002c"`);
        await queryRunner.query(`ALTER TABLE "appointment" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "appointment_translation" ADD CONSTRAINT "FK_3e21fd50c9d1be374b3b620002c" FOREIGN KEY ("translatableId") REFERENCES "appointment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "appointment_guest" ADD CONSTRAINT "FK_0bad2851364dbc370bad0683c53" FOREIGN KEY ("appointmentId") REFERENCES "appointment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
